apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-cluster
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: postgres-operator
      version: 1.8.2
      sourceRef:
        kind: HelmRepository
        name: zalando-postgres-operator
        namespace: flux-system
      interval: 15m
  # See https://github.com/k8s-at-home/charts/blob/master/charts/stable/zalando-postgres-cluster/values.yaml
  # values:
  #   postgresql:
  #     users:
  #       postgres:
  #       - superuser
  #       - createdb
  #     databases:
  #       keycloak: postgres
  #     postgresql:
  #       version: "14"

  #   # superuser: {}
  #   #   password: admin

  #   persistentVolumes:
  #     # hostPath: /media/db/keycloak
  #     replicaNodes:
  #     - k3s-dev-1
    
    # dumpBackup:
    #   enabled: false
      # type: custom
      # volumeSpec:
      #   nfs:
      #     server: "${NFS_SERVER}"
      #     path: "${NFS_KUBERNETES}/${CLUSTER_DB_BACKUP_PREFIX}/gitea"
      # subpath: "."
      # schedule: "@daily"
