# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:VYc5Vham7Huin+uX4JLFT550+vI=,iv:YifaoXsqRn5H6rXm02v1skeThSn9x1P4un4rCEt3u3w=,tag:/Lh1FC0VZSWprbW/wnIa4A==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:n+/34qFPRiwIGsVk2XqQC45DkCMYtpWD56Gy2OgQpxn5WZObBA==,iv:W7P5Do80G1wCovyLTlJ58HDQdc6OVx3GPB4+cjLaW3E=,tag:fQt8g5Uk5TLwSRwawAgJOw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:WykWmlkPAHtlA2ZwJOIGhIaDQQ==,iv:OWFmPg8TOAw3zwRhIDk7e6puiZC9iGtkaO8EfsPa/P0=,tag:gBWSJivJ49P7RRm8FPQZrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q50xz97syrgwskahjc7qrcn6wsl2a3je2n88fd0rsf8jk07q23usdw2a0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cGdiNDFZNlRTdm9CVmo2
            N29INjVDL3FwZGlWeGwzNkFxZWg5b0JQYmtjCjN3OEhQZnY5MVQ4L2dhcVZ1dzIx
            UDR6eDdVUENmeWxUMDY4a0JYbjZmZEkKLS0tIGJsTU0xZ2gveVJTQ2xtbWtQeWNT
            UFpiTWpCQzF1a3p6TVo1eG5jYjRzd3MKHuGbbRkShDapzEVL3CWtdCf7avBk1fVz
            V9a067M6gaob5zoA6bApCFOA1tr1JmntcsSf8GGPA1Wi+1pJplBmQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-10T12:55:23Z"
    mac: ENC[AES256_GCM,data:AgPMm4urS3S82O8fHvH1OXZ8IAdPvjJiVw8dTJuU0dnUEO9KEKNvDHqvoX4bru35mYxmIKPUNZ+EYyDHSIkIjsSTN+3k4sT5EC6c+/dHdrryvE3XPK1Y0rSJLwwGFluLYMUNDeZUg2zSyLWY+d1QA4TkaXhdCa75bVXmio9SnjQ=,iv:Vyay15qPX1flFtQxujSNw0aVZw8axhE74PEqwBouKOE=,tag:U+rRzSl/+xfnDa0zXSjOrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
