# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:AD8tx01qE/jAVPkOC0rx8simhaA=,iv:+OVD+R4VVi/46F+3dt3p3g3te77CPGVnkS23k6giM4k=,tag:wmuxMtRAlkDQ4rTAaJvF3A==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:tR34VNObAmosZmPnRkhXqhatEWPH4A7/ZTVn87rlE6RrFAebVQ==,iv:Br4qgSWyryQigmof4TERxC2aTXSVBllygeWnkplGPxY=,tag:FvaWxWmTxqcacZvGRzHEig==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:W2SyY1HkJRJmUXHibWOycGiS1g==,iv:QH/JQKs5Ww31w1j8ybCp54fzYX4vvrDUj2BXFxVwLMQ=,tag:2pRd3G90Tz7+E2mp8IhgBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q50xz97syrgwskahjc7qrcn6wsl2a3je2n88fd0rsf8jk07q23usdw2a0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQVdvakZTVnhkcHdJWUZI
            MWJNRzFhUlJudjFjUkhKK0UwY2VEb3JNREhVCllXMmpxdTJwSkRxY0kxN3YvcGRY
            dzNTR0U2UE1XcEdmaUZzL1N3a200ZTQKLS0tIDZNTVJhMnFYQVFrbFhiZmxZb0pu
            TXdCUTB4U3E0NjJiMU4zd1UvaFdBcnMKCXzlG12npzzV2afM1sPQFRo2L4ClMV99
            mk5h0u66iuJGQf/rxiL+u5+gBSIVJjNq35IwiUySAuQtOVbKY5wenQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-10T15:12:43Z"
    mac: ENC[AES256_GCM,data:UVejtJkqdSmtXd87wGCKJ6PuhDxXZWIMs78n9NVkeSq733esyQv0iD5HP5KEat7oCWsEHiu0PnZ5+gSpFGfI2bLa3Uj/jpLzJbTj7T4jWEmlUrMjjIBVXUK5WVq3aYWDC5UpTgyYAbxwqU8VrRR2FoNTKZUwxy9x5tNlAeE71WM=,iv:kF/pB2ovuUDYYKEFrcU5zfV3gEDf2eAKexw7wjbUGhQ=,tag:aCPZtI+Hb9iLkUZbCWytXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
