---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 12h
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # csi:
    #   attacherReplicaCount: 1
    #   provisionerReplicaCount: 1
    #   resizerReplicaCount: 1
    #   snapshotterReplicaCount: 1
    defaultSettings:
      defaultLonghornStaticStorageClass: longhorn
      defaultDataPath: /mnt/storage
      replicaAutoBalance: "best-effort"
      dataLocality: "best-effort"
      storageMinimalAvailablePercentage: 0
    ingress:
      enabled: true
      ingressClassName: "nginx"
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "database"
