---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raspberry-pi-client
  namespace: default
spec:
  selector:
    matchLabels:
      app: raspberry-pi-client
  replicas: 1
  template:
    metadata:
      labels:
        app: raspberry-pi-client
    spec:
      containers:
      - name: raspberry-pi-client
        image: ghcr.io/rustygreen/raspberry-pi-client:main
        imagePullPolicy: "Always"
        ports:
          - containerPort: 80
        env:
          - name: RPC_CONFIG
            value: '{"servers": [{"title": "Basement Pi","url": "https://pi-basement.${SECRET_DOMAIN}","pinLabels": {"11": "Cows water","32": "Cows water drain","15": "Chickens water","36": "Chickens water drain"}}]}'
