# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:RefBBGs0dIkmt/jNMAlNGl7kos4=,iv:AYPAZEWNS/24CWGRKEJRC9KQ2bMoav4R/G/LACo5eTE=,tag:rMISSpoivwutyf5jmPLIYg==,type:str]
    api-key: ENC[AES256_GCM,data:b8n6QIzA+MF4oOG4jGaOtr6kdSgX8JrzPCpqhB/Fdq25mRX7Wg==,iv:t40ZC5zskpw+JllYsXHKIB2lO9MTT6AIP5wxu6k07qc=,tag:x7LKugtM4aIk4AwtwXA28A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q50xz97syrgwskahjc7qrcn6wsl2a3je2n88fd0rsf8jk07q23usdw2a0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaUNsenp0SGkzUDJSbTJw
            YmVoWGlKVzF3SFpmVnlzUUI0blc4QUxyRUNBCmVGQTczVVl6ci84NHNKaWlsLys3
            SEdpb1V5M2hyaWxPeU10WE4wZlBmbVkKLS0tIHRQY1UvTThaSVJGYlQxdmVYOEJF
            c3lONnFjUEtoNkZmaWhpUlBCQVh0RzgKxKNn9BrXnxlMcobmjgUJiNVjja8V3Mhd
            ltHfqj/xr8G/WO1K207SDu4axXxIQqJ7+i/zj8GS07T64WxKotw8ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-09T16:05:18Z"
    mac: ENC[AES256_GCM,data:/JXvrGx+Ztq0nf4pEJ6+bj15EL3442RvoSRgFci1o+kwJCWChz/xkWnyWpWL73z9HMZf3RDryHkz31yGqRBjNXpg57PhGLZ1EPlGUe4Juot7GdRZ2MunM0m8M3Ntgr/H+e7WkM+mZq0yhgpyjpqaAW1yJ/65IK7WOtM0Xef/g6I=,iv:tGkEwv5MZ/N9ADT55l2pZ81jRN3I0jEgnBMPKgroWvs=,tag:HqFZImypRmlM/d100ZlCfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
