# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:XSbULgO//Tcvur4ctSWLYYsQfsk=,iv:PVhD2SYlkXDupvy6PtWifDVX3D57fsgFt1m24Cf9j9M=,tag:qHAk/t65E5738//0h80UoA==,type:str]
    api-key: ENC[AES256_GCM,data:PtJhhprdcl3umo0HbyCWG1AEn9d989+ROM5AwpJtRL3IfhXDuA==,iv:2TWp9acs+KN7MT+xE1fvO7ags0vyR5IOOsJgxQxNdAw=,tag:rtAWxIwMSu7PT/RTuGc3xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q50xz97syrgwskahjc7qrcn6wsl2a3je2n88fd0rsf8jk07q23usdw2a0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVHJYUmFoNXFTL0RmYU9v
            d3dMbDNOWjFNRWxjZ080UVNPSEJWWnZZZ2tFCisyMzUvbHhRV2NQY2dDcHM2bWE3
            bysxZkZyODZWNks4RmJBa09UUEFDOVkKLS0tIDBEQWZaVUhnREhHS3RzZUdKUkNJ
            OExTWmJlY2ZPOWhsQjlmT3BFemV6N0kK1PhLCe7gaPmMwTXYW4I80TgL7Y6aQbTx
            SvIr4k1pmxbJ236hDY2M6kxVfxpbKsurDWkU0eJpUmkCVkNRXWPI2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-10T13:33:19Z"
    mac: ENC[AES256_GCM,data:9IqC2vwkdZwd5VO4lJFivG7PkLTla5JUSjLpcd3EENj1ZE87Or+H+m4X2DOz5nzqPfH0xOJ/lOwSII65TRN/aSVCQyUgdobc/RfHWRtten+j4hlhlCxiY/psUq7a+v5G6qtg1/58JcPDU94l4l0nYP243ua8WgHWiENlF1D5lIQ=,iv:nBuDGBRUyNGiaQw50mVZehFz5qSj5OV9Mbhpc9lizCs=,tag:ZOWgaZ2ewq6lDVexiVfbsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
