---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/New_York
  METALLB_LB_RANGE: 192.168.1.200-192.168.1.202
  METALLB_INGRESS_ADDR: 192.168.1.200
  METALLB_K8S_GATEWAY_ADDR: 192.168.1.201
  CERT_CLUSTER_ISSUER: letsencrypt-staging