# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:plHYEsYNHpTnE7Q=,iv:a7jfl//NiwYObWpbxvjVp1XEqjrYDMzHfngQ5RMJrbU=,tag:hqBMmovdVjAAcVQ3b0DWSA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:XFUcTId1e8NaNfOh20LQIRq+m9c=,iv:4ZkjzoHqvzwQsShXkaM2EBLEBuOueeIDa31V3bxj8Lc=,tag:xrIF5P7rjMiC/uK0mhJ5Wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q50xz97syrgwskahjc7qrcn6wsl2a3je2n88fd0rsf8jk07q23usdw2a0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRUp3THYyNiszeHpibVlK
            TXg3R1V2QUtLZmdCUTRPVkZrdFp1R3JuOGlZCk5TMkxXTkowVVhuNWpIRmJoMVlu
            a29rUEwrUGxQZHNkbjVjWU9NQ0l4ZWMKLS0tIEFGS0pLSVdkeVhIZmZVRjBhOFVv
            cGIzVjEvVmNMTDZEVWt0cUFsbWNhMFkKkfRhAeuAhh+zgHyNYDNwwo1MH5mE4CPM
            EbKbBNqFk7QsiQggFA6h4kEFv34qIAVBPYVEv6wNFSK19LAoEHwfIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-09T16:05:18Z"
    mac: ENC[AES256_GCM,data:Q3v4rlvbYNUN/BCI46bpoM3jP74hJ5ephTID7AwaGxJw4tN6AdPej+zuFbFW0VBbvr+Wh15jEMi8wCIalFu4gBRHL8a+YQDwfa3i8FmdlmNQTyXJUwXYwg8BoIlpPDjTZo3uDC1ZvcnLac9gbSGLI+qh3BbzkafIZnxQ4b5Wbk0=,iv:UIgPBKi/22+oI2FdQF6EkWZcrhcaJUTbdbTIyVOpqM4=,tag:6YWr1PPAuKhglzSC91eegA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
