# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:kkYhMctj4Oj1ivWPJkU=,iv:EkCoR06qOl091oO4zAw5fbxDpaHbfMnTYmIGKVF6SOo=,tag:6FFZJZ6LcSNiT2VEHYQMQA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:g41y0FGkkgQI7zX0baeI/8cK9GM=,iv:4v5eKXjZmaun3B+cdviwbSwO6Dw4NP6FNLNI9bMkJ2c=,tag:H125PWmdUTK72/NiF79RCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q50xz97syrgwskahjc7qrcn6wsl2a3je2n88fd0rsf8jk07q23usdw2a0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eWVCWFNaUkxTbzZpM3ZL
            Y001S2NvTkRJZ3NuZkF4U29KRlhLalB0N1VzCkFUdS9uQm9tV1Zxbi9rZEJudFNU
            YXlRZDlDcUtZS2NOMkYyY2ZQNnRkVncKLS0tIEQxbW9BZFExOXQ5K0xQaTBxU0lQ
            b3cxa1JMZjVCOWlXNnYxZGNNMEkzZjAKeAuL6tqwNKF8Amicrg6wd5tx7Tm+dHK5
            HxCP3fASrjvXDIzVa4RzPOI/xLK4P6zxLqc9YArTBFdur/62JMcCZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-10T12:55:22Z"
    mac: ENC[AES256_GCM,data:B9XJqVx85B0dld3uOUhnLW6w2SYUGMREsyDPNhNU5J2zW1D8b5BkJPozdHILbHqnDSWy8IYVOzNpghQOybm6D849n70ycvuN9MtwyRbkRkRcQiKQYI7itMEkhF9iXWW3JPdrgx0KK4HwKMBOqPOTX9FL34d3PtXBm3hjOKrtsBw=,iv:JLkBByJ64ZBEkIXkSYi2gKeHP0IqjqgVaRxh4jivBqk=,tag:Man79yB7stnc39cJ6QroXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
