# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:edGTq1s8KJIZAxKiMjM=,iv:Szkv/DIuMNgMWeQ+ZuiB7V5nMCeFMMZmEHBStCw06aU=,tag:HxUWbR9y8gGfHTQR+WGQTw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:uBhM+bWs2S4pftKYGZ53NhbtocQ=,iv:+uyBraZKGKHAHpZMCK3lGk1SODzj4A8to+96cKIBaUw=,tag:vo0GcLYBsogXPoEayYAoJQ==,type:str]
    SECRET_ADGUARD_USER: ENC[AES256_GCM,data:Z+x39oo=,iv:oy60ijgwLXq7kfvcDVDmkpC5Dsg7TiJnwIrt9jMwQuc=,tag:WJunmFdaZemZWmAa3hEBAw==,type:str]
    SECRET_ADGUARD_PASS_HASH: ENC[AES256_GCM,data:dr32yjdNtumnsndIn+nr4iVreWo7e71prOB8E6A+PJn1ovgeGbm9t8mE+RsGvm7N5crD2BV/Rb+BT3lOBBPPTby4,iv:trOg1vhxrD+Sx73TKy3PGrzM3mywxa+UUA/SgKcUGZo=,tag:QQxsWtHXjnc4hlWSu3RI2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q50xz97syrgwskahjc7qrcn6wsl2a3je2n88fd0rsf8jk07q23usdw2a0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdHlKeTVOcnpjSEplVU96
            US91dkh4bUxvRGdiby9jOUN5ekR4Zi9RQzF3CkNnWWRCY0NVOGExT2Z3RFIwRlRM
            SFh0ZnJMYnNCclRadTlPNXZ5dGovVE0KLS0tIC9mSzN0Lzk0Q2xhL0EzY1pnTUlX
            dFcvcDJtaktiREFiZU4xQ0lkbXE1eTQKwX9HGFeQVm1zq19vs2RbIqdUCCqLaQ9F
            qHpnGHg1JTZZ5mV7IzyB0k/N843N5ss26S4pE5E8mdzMFTjvndM2qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-09T17:42:20Z"
    mac: ENC[AES256_GCM,data:LS4KHrbcWUeYo/CdFOguaO8qeSvEPUWYXTkEANnrMWFBfYtJL1hJY/rqX9BxUZgq0RaWkP45vXWt3gG6RjmlL6zB20tXebXgYCFgQweh5Q+23nWUKi9l9n4dJNw1rGIu8rDpkI1Qh7zTkeKHtX7DYUExohil3THWFr7Gt2W7d+w=,iv:tTVENnCO71+5QDtjxsdBbKIib7DOJyU0dIlAOrkpg5M=,tag:vEUhyBdUp0wP+G6sFkTDhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
