---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime
  namespace: monitoring
spec:
  dependsOn:
    - name: longhorn
      namespace: storage
    # - name: ingress-nginx
    #   namespace: networking
  maxHistory: 3
  interval: 10m0s
  suspend: false
  releaseName: uptime
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: uptime-kuma
      version: 1.3.5
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    fullnameOverride: uptime
    image:
      repository: louislam/uptime-kuma
      tag: 1.17.1-alpine
    env:
      TZ: ${TIMEZONE}
      UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: 0
    controller:
      type: deployment
      replicas: 1
    service:
      main:
        ports:
          http:
            port: 3001

    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "thermostat-box"
          hajimari.io/appName: "Uptime"
        hosts:
          - host: "uptime.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "uptime.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        existingClaim: uptime-data
        mountPath: /app/data
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 250Mi
