kind: Secret
ansible_user: ENC[AES256_GCM,data:xRotLm0=,iv:PZ9/aD1NmVVRbc1lvjWRijTShcdg11HddpzTWbCA9Qg=,tag:dUmETy/nIhAn8GlB2fKqmQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:0VnvBqdufnXR9mg=,iv:zww1EIBaz3z4kRJWpyTYCZKJmxOlTrOrK9SIpOM3hDI=,tag:KSUV8rkrzXlgVSNdg6Fj3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q50xz97syrgwskahjc7qrcn6wsl2a3je2n88fd0rsf8jk07q23usdw2a0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZckRYcWVtSzZDN1ZwZjdI
            Y0xMNkYvbVNrZysrcWZVMm1OTC83MEovUVZVCllwcXpWalAyLzViSGNwSC9SYzJU
            Ym4yREk5RmlLQnZxUFpVQ25HYWlTancKLS0tIEhWWkM1MGcxTFhpdUdmSjhRaFhK
            VXhFMXpvbzI2YldOTGI5K1lsVWV1RTAK20N7ihD7ipJL/FB1CBrid0CFf5d2UjpY
            9KXsGJQHPbsWct/G20fbW1akLH7qBbqOr6eZIrJCyCFMl4uObXOjIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-10T13:33:19Z"
    mac: ENC[AES256_GCM,data:nLLDk8Uvu89am0q17KSAl1hGXjEzKAFFCG+vWaIwmjoBRf22qQdnaNEHO0ibhPYD8EC0jgotVHLJ11vVsv85YkpD1IJ+SWJ3Xz4zT7W+4PEXb8XiHI+Zu1CkdPlDpLOusBK2297cE6RXPBhxqqdNHOxLeMLI10LFmW3eNOW11Fw=,iv:ZAETdaZRrzY/0E8dMtHoLAKBLMANTD+Z4hkt1NAtHgg=,tag:94m4iHV19boFK26ddTuxTw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
