apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: photoprism
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: photoprism
      version: 7.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    env:
      ## See other config options from PhotoPrism documentation: https://docs.photoprism.org/getting-started/config-options/
      TZ: ${TIMEZONE}
      PHOTOPRISM_STORAGE_PATH: /photoprism/storage
      PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}
      PHOTOPRISM_SITE_URL: "https://photos.${SECRET_DOMAIN}/"  # Canonical / public site URL
      PHOTOPRISM_SITE_TITLE: "Green's Photos"
      PHOTOPRISM_SITE_AUTHOR: "Rusty Green"
      PHOTOPRISM_ORIGINALS_LIMIT: 4000 # in MB (default 1000)
      PHOTOPRISM_THUMB_FILTER: "blackman"

    envFrom:
    - secretRef:
        name: photoprism-env-variables

    persistence:
      config:
        enabled: true
        mountPath: /photoprism/storage
        existingClaim: photoprism-config

      originals:
        enabled: true
        mountPath: /photoprism/originals
        existingClaim: photoprism-photos
        readOnly: true

    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
          hajimari.io/enable: "true"
          hajimari.io/icon: image-multiple
        hosts:
        - host: photos.${SECRET_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - photos.${SECRET_DOMAIN}
