---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-photos
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Ti
