---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 12h
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    defaultSettings:
      defaultLonghornStaticStorageClass: longhorn
      defaultDataPath: /mnt/storage
      replicaAutoBalance: "best-effort"
      dataLocality: "best-effort"
      storageMinimalAvailablePercentage: 0
    ingress:
      enabled: true
      ingressClassName: "nginx"
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "database"
