# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:P88K99RypNbX/Lls8Sv9m0qLSxX6W3S9igYzIrmXLR9Pse3i32DpUg==,iv:tiOFTvW0nqfDqXEuQoiiBpQYTbag58xLGjh5mnetMnI=,tag:p3ktq+NucVcLvcvJm8AGAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q50xz97syrgwskahjc7qrcn6wsl2a3je2n88fd0rsf8jk07q23usdw2a0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYS3Y0UHRmaTNVOTlrYXlp
            SUIvWVhTb3FIcTZ1elp0cGRpYTk4TGhQaFgwCkg5eHk2RVE5dWsveDIwaCtqVWhG
            NlNvbDQ4empLV0t6R0xZRC9uaWxJOGcKLS0tIDZlR3pJNzNvT0xqUkllN2ZMRWFw
            a21wRnlveGlmZlVRQncxb0VBSTZ2OTgKBlbNUtwcGiox9951RZZCJuzpCEwaNjGB
            ggt+D2JUs73EVThYvgUUsLkJyvDmkOMl+hhEfkILO5zYTB+3/PR8kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-10T15:12:43Z"
    mac: ENC[AES256_GCM,data:GkTorgGxDy1mjc4uWiXMCTHS8j8aiicLCQ/DCBbJmFIDKDE8Qtkz6KLqjdktyIAwP7OYypguBV40zGas/30adLTTi1d+UmHrb844VW3pY5BsKUXdZCnhZNxDWyV5ouliRUcF1s9WFuDNctWsLvxQu3vj8geKGqitUzwNT+uYm4Q=,iv:Rv2WjFPZVhYkg5w3CJSwhCba18UjQYeU9Y0v/Wt1FPI=,tag:ixbMQns3r11bparb8Fxfcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
