# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:hR9r2iqg00anUukwXyFdpU/Fx0nij/VbWfWYTAj9hxfICcmOlMapaQ==,iv:9Nqeg6T1b67ZJevCXBa4IFG6Mokce2+VR7wMoP4Nh5s=,tag:PVqt75ACZemz+EtlbZz1Yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q50xz97syrgwskahjc7qrcn6wsl2a3je2n88fd0rsf8jk07q23usdw2a0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTHc0VFVmZkVOejEzS0Fw
            TTQ5dXJwdDloc1QzSzVxYklqSGpQZXBRR3pFCkJJSXRwMHhoUUMzdE5rditkMWRz
            YUtxbEdzbUZ6a0c5ZkplUnk3a0JhUDQKLS0tIHQ2aHdjNmpHRHBxY2tydjUveS9R
            UUc0SWNnU0NkV1dscE5yUHpsejRmSEkKI5RlppWIu8V+A6VM5nNRFgnpq18UJf4l
            gZmGFo/10X6e7i1eDgiMN3UajRqomr3kgOXb/Sj2Fr4Lt2E6SH4IYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-10T12:55:23Z"
    mac: ENC[AES256_GCM,data:l8EfWP2Rf8h0667i6C3oKlYqSZpHnZYRuU+h7jvKTkxpTa1pnwRD1d6RPeL2bEek99CbnBetmpRu9mdsavf9oVPWDew1PJCF2eMjFSfEAUXSjHTqk+8W03DL4uGkegmlAH5CtsfL3euPOoQsTDBUjRyYVqIKffDOcFr4mYkdjfo=,iv:DCWsW9pfCpWK+S3ypuWN0Iw7OiRlvzmzUrWOFg4+Mfs=,tag:QIsHAFI8eUGgGBI3YA9Xng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
