# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:w1vluxkpQ4rc476bOpg+n4IMX4j1jjFU8Vf1Z9mv9iGwK41+nv/p4A==,iv:jZwncDWNwNl+KoTy0ni1eWQM15Tuzfq+ihPH1pq46o0=,tag:c9RonM+p+ICa/PE9OSEX/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q50xz97syrgwskahjc7qrcn6wsl2a3je2n88fd0rsf8jk07q23usdw2a0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Y1dXMmcraGtEKzU3NkVI
            a1JoMEp0QkVpNm9VUVVFcEsxdnRrU0swNWg4ClJ1MkRwTndacmlBZnJ3bHY4a1ln
            SStwQ3V6eC9iMGRmbFJBVXlxZ1JqZjgKLS0tIFpOK1BlQnhCdVgxbEo4aGtQd3Ux
            b01pMVZkS1pEVFZybWJRZ1ZiU01ueHMKh5ZTwQiBz3uq7hXjxRxGfLbzISxoAKiv
            kC1202LRAGDOwE/jKQlQhMiSuoK/XwhhZWeClCoYAQoqcSruyZgWeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-28T14:30:36Z"
    mac: ENC[AES256_GCM,data:VFdAQI1gQmxmeffFcdkguul82vfar+lCYZ98kgWwJlmSPQe2cBKijKiVBlM3t76KQkjYbEjO6GqEJk4bkefbuv7YFa+AdwtbxqQMjWQKYAxoRf0KG5LTt+lyWUa/lUSU2/Va1mMz1w6yakNNwOoA1lWLeYviYlC9kGP6jeHaiq8=,iv:+aNjPdwlEdBl1v75fPRKwgLj+Ci8KBRaJnyXhGpOtyQ=,tag:VK/DxvEdweWcNOCag+7ICg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
