# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:dDKOJc50POm2wMiTIERb/bsOTYqsWdzHd6Ymgw06NQ6Lx+jHsDe2QA==,iv:tpdg6f34Q4BuTIY7Rcuxofx+ZJJ+j/EhUjELg5Qjb00=,tag:bk3mgnmm+EXK35i99SO1Wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q50xz97syrgwskahjc7qrcn6wsl2a3je2n88fd0rsf8jk07q23usdw2a0w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVmVKYnlhbUw1MjZLODZZ
            cTVmemRCZUQ3RG5DemxJVVFmUndLd3VYOGo0CjYyNmFqb2FGdy9ROWdNd0dpdUFY
            anVqNDFjSFZXKzZjaFZ3MXMwZlg3RWcKLS0tIERFcnRhSE9NenhYYTN3RGdqaEdW
            SWxYM2RtZzFXVktiQ0c3dEQ1bjJVRTAKo+Kp9q6Zytxr5em73GO0E1LMReh+MJmy
            dQxcQE89qEtyx/8ddnR8rjb1YnZrL4Frlxi3MPXHBwX/U/pM5ms9HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-09T16:05:18Z"
    mac: ENC[AES256_GCM,data:/+LaC67MQVzoK+HoN80AtuJ+u9zhnBpWIn3CjN03IQr052yC8qetzviaN65sPvsnGJjKNDCwUcd53kSrnjl0wWOdqT+yIfHep0Jjxq0qQekArUaPKzVM7Hml96toNfWnWT5YHYq1v/NFO1JV/taV/1T6hGuVGBPb3Da758h0EYw=,iv:7dz4/g5iVdKsfTx6upmwtxMt7BcOcLEz1ecbhpeIqfk=,tag:xGtlbHku2X6LExtnDn4lJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
